---
title: "bis15l_project"
author: "Sidney Parel"
date: "2/25/2022"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
library(tidyverse)
library(janitor)
library(lubridate)
library(maps)
library(ggmap)
library(gganimate)
library(gifski)
library(transformr)
```

## Load the U.S. clinical cases data sets.
The reported clinical cases data sets for the years 2016 - 2021 contain the 
same variables but do not have the same column names. Therefore, before merging 
these data sets, we standardized the column names and removed missing values.
```{r, message = FALSE}
## Load the reported clinical cases (rcc) data sets:
# Obtain file names.
rcc_files <- list.files(path = "Data/us_clinical_cases", 
                        pattern = ".csv", 
                        full.names = TRUE)

# Store all data sets in a list.
rcc <- rcc_files %>% 
  lapply(read_csv)

# Rename the data sets by year.
rcc_names <- list.files(path = "Data/us_clinical_cases", 
                        pattern = ".csv") %>% 
  strsplit(".csv") %>% 
  unlist()
names(rcc) <- rcc_names

# Check if the number of columns is the same in each data set.
# for (i in 1:(length(rcc) - 1)){
  # print(dim(rcc[[i]])[2] == dim(rcc[[i + 1]])[2])}
    # number of cols in 2019 daa does not match 2020 data
    # number of cols in 2020 does not match 2021 data

# check the columns in the 2020 data set.
# rcc$reported_cases_2020 %>% 
#   colnames()
    # Empty columns

# Remove empty columns in the 2020 data set.
rcc$reported_cases_2020 <- rcc$reported_cases_2020 %>% 
  select(1:4)

# Check that number of columns match in all data sets after removing the empty 
# columns in the 2020 data set.
# for (i in 1:(length(rcc) - 1)){
#  print(dim(rcc[[i]])[2] == dim(rcc[[i + 1]])[2])}
    # All data sets now have the same number of columns

# Check that the column names match across all data sets.
# for (i in 1:(length(rcc) - 1)){
#  print(colnames(rcc[[i]]) == colnames(rcc[[i + 1]]))}
  # The columns contain the same data types, but the names do not match
  # across all data sets.
```

```{r}
## Standardize the column names and variable types:
# Create a vector containing the new names.
rcc_col_names <- c("jurisdiction", "any_cases", "clinical_cases", "range")

# Assign the new names to all data sets.
rcc <- rcc %>% 
  lapply(setNames, rcc_col_names)

# Change the character column variable types to factor.
# for loop solution
for (i in 1:length(rcc)){
  rcc[[i]] <- rcc[[i]] %>% 
    mutate(across(where(is.character), factor))
}
# purr solution?


## Add a year column to all data sets:
# Obtain all years in the list of data sets.
rcc_years <- rcc_names %>% 
  str_remove("reported_cases_") %>% 
  as.integer()

# Add the year to all rows.
# for loop solution
# for (i in 1:length(rcc)){
#  rcc[[i]] <- rcc[[i]] %>% 
#    mutate(year = rcc_years[i])}

# purr solution
rcc <- rcc %>%
  map2(rcc_years, ~mutate(.x, year = .y))
```

```{r}
# Merge the data sets:
# Drop any rows with non-clinical case counts.
all_reported_cases <- rcc %>% 
  bind_rows() %>% 
  relocate(year) %>% 
  arrange(year) %>% 
  filter(!is.na(jurisdiction),
         !clinical_cases == 0) %>% 
  select(!any_cases) 

# write_csv(all_reported_cases, "all_reported_cases.csv")
```


## Load the NCBI Isolates Browser data.
```{r, message = FALSE}
# Load the NCBI isolates data and select the variables of interest:
# Load the data.
ncbi <- read_csv("Data/ncbi_isolates.csv") %>% 
  clean_names() %>% 
  select(isolate, create_date, location, 
         isolation_source, isolation_type, snp_cluster)

# Select all rows associated with US clinical cases.
ncbi_clinical_isolates <- ncbi %>%
  filter(str_detect(location, "USA"),
         isolation_type == "clinical",) %>% 
  drop_na()

# Remove "USA: " from values in the location column to get a state column.
ncbi_clinical_isolates <- ncbi_clinical_isolates %>% 
  mutate(location = str_replace(location, "USA: ", "")) %>% 
  rename(state = location) %>% 
  mutate(state = factor(state))
  
# Change the values in the isolation source column to one of two categories: 
# blood and other.
ncbi_clinical_isolates <- ncbi_clinical_isolates %>% 
  mutate(isolation_source = 
           case_when(str_detect(isolation_source, "blood") ~ "blood",
                     TRUE ~ "other"))

# Change the remaining character columns to factor.
ncbi_clinical_isolates <- ncbi_clinical_isolates %>% 
  mutate(across(where(is.character), factor))

# write_csv(ncbi_clinical_isolates, "ncbi_clinical_isolates.csv")
```


## Create an animated map to show the clinical cases in the US since 2016.
```{r}
## Create an animated map for the reported clinical cases:
# Load the state boundary basemap.
states <- map_data("state.vbm") %>% 
  tibble() %>% 
  mutate(region = factor(region))

USplot <- ggplot() +
  geom_polygon(data = states, aes(x=long, y = lat, group = group)) 

# Join the reported clinical cases data to the state boundary map data.
#   rcc data has state abbreviations, not names
#   need to add a state name column to the rcc data
#     make a new data frame using built in state name data sets
state_key <- tibble(jurisdiction = state.abb, region = state.name)
all_reported_cases <- inner_join(all_reported_cases, 
                                 state_key, 
                                 by = "jurisdiction") %>% 
  mutate(region = factor(region))

# Join the reported clinical cases data to the state boundary map data.
statewide_cases <- inner_join(states, all_reported_cases, by = "region")

# Since some states had no cases, they will appear as empty polygons in a map
# Need to create an additional data frame containing the names of states
# without cases for each year so that we can fill in the empty polygons

# Create the not in operator.
`%!in%` <- Negate(`%in%`)

# Subset statewide reported cases by year.
for (i in 1:6) {
  assign(paste("statewide_cases", rcc_years[i], sep = "_"), 
         statewide_cases %>% 
           filter(year == rcc_years[i]))
}

statewide_cases_list <- list(statewide_cases_2016,
                             statewide_cases_2017,
                             statewide_cases_2018,
                             statewide_cases_2019,
                             statewide_cases_2020,
                             statewide_cases_2021)

# Use the statewide case count year subsets to extract states 
# with no cases for each year.
for (i in 1:6) {
  assign(paste("no_cases", rcc_years[i], sep = "_"), 
         state_key %>% 
           filter(region %!in% statewide_cases_list[[i]]$region) %>%  
           select(region) %>% 
           mutate(year = rcc_years[i]))
}

no_cases <- bind_rows(no_cases_2016,
                      no_cases_2017,
                      no_cases_2018,
                      no_cases_2019,
                      no_cases_2020,
                      no_cases_2021)

# Join the extracted states to the state map data to create the data frame
# containing all states with no cases for each year.
no_cases <- inner_join(states, no_cases, by = "region")

# Draw the geographical map.
fig <- ggplot() +
  geom_polygon(data = no_cases, 
               aes(x = long, y = lat, group = group), fill = "gray") +
  geom_polygon(data = statewide_cases, 
               aes(x = long, y = lat, group = group, fill = clinical_cases)) +
  labs(fill = "Count") +
  scale_fill_viridis_c(option = "mako", direction = -1) +
  theme_void()

# Animate the map and save as a gif.
fig_animated <- fig +
  transition_time(year) +
  ggtitle('States with Clinical Cases of Candida auris in {frame_time}')

animate(fig_animated, nframes = 6, fps = 0.5)
#anim_save("us_clinical_cases_map.gif")
```

